budget_per_frequency: 
budget: 50000
frequency: "BME"
risk_free_rate_source : "yahoo"

asset:
  - name: "SPX"
    weight: 0
    source: "yahoo"

  - name: "SX5E"
    weight: 1
    source: "yahoo"
    