budget_per_frequency: 1000
budget: 
frequency: "BMS"
risk_free_rate_source : "yahoo"
target_portfolio_return :

asset:
  - name: "SPX"
    weight: 0
    source: "yahoo"

  - name: "SX5E"
    weight: 0.33
    source: "yahoo"

  - name: "N225"
    weight: 0
    source: "yahoo"

  - name: "HSI"
    weight: 0
    source: "yahoo"

  - name: "GC"
    weight: 0.34
    source: "yahoo"

  - name: "NASDAQ100"
    weight: 0.33
    source: "yahoo"

  - name: "SI"
    weight: 0
    source: "yahoo"

  - name: "PL"
    weight: 0
    source: "yahoo"

  - name: "PA"
    weight: 0
    source: "yahoo"